name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda diariamente à meia-noite
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: eduardo7660
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: 🐍 update snake animation
          add: "dist/github-contribution-grid-snake.svg"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-contribution-grid-snake
          path: dist/github-contribution-grid-snake.svg
